version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: local_sql
    restart: always
    environment:
      SA_PASSWORD: "YourLocal!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  mywebapi:
    build: .
    container_name: mywebapi
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
